### PR TITLE
Add universal similarity score

### PR DESCRIPTION
**Pull request by erik-dunteman**
# Description
In this PR I propose the "universal" similarity score, which provides the answer to life, universe, and everything. As one would expect in a proper embeddings DB.

# Implementation Notes
Do note that this implementation depends first on cosine similarity to form the shape of the response, before then replacing the similarity with the correct answer (to the life, universe, and everything). I accepted this computational overhead as acceptable, for it is no easy task to calculate a universal answer.

# Testing
This is untested. But is correct.

### CODE REVIEW

**Comment by jdagdelen** [comment]
Good, but can we rename it to "Adams" universal similarity to reflect the philosophical influences? Also, want to avoid users thinking this is the metric to turn to first over cosine similarity.

**Comment by erik-dunteman** [comment]
I considered Douglasian or Adamsian, so am open to a rename. Will update to "adams" and push in a bit

**Comment by erik-dunteman** [comment]
Done @jdagdelen, thank you for the opportunity to contribute to this foundational project.

**Review by jdagdelen — APPROVED** [review]
LGTM

**Pull request merged**
